// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// algoritmo_logit
List algoritmo_logit(arma::mat y, int nit, arma::cube beta, arma::mat sigma2, arma::cube f, arma::mat alfa, double sdpropbeta, double sdpropbeta2, double sdpropf, double sdpropsigma2, int n, int p, int j, bool display_progress);
RcppExport SEXP _fatcat_algoritmo_logit(SEXP ySEXP, SEXP nitSEXP, SEXP betaSEXP, SEXP sigma2SEXP, SEXP fSEXP, SEXP alfaSEXP, SEXP sdpropbetaSEXP, SEXP sdpropbeta2SEXP, SEXP sdpropfSEXP, SEXP sdpropsigma2SEXP, SEXP nSEXP, SEXP pSEXP, SEXP jSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< double >::type sdpropbeta(sdpropbetaSEXP);
    Rcpp::traits::input_parameter< double >::type sdpropbeta2(sdpropbeta2SEXP);
    Rcpp::traits::input_parameter< double >::type sdpropf(sdpropfSEXP);
    Rcpp::traits::input_parameter< double >::type sdpropsigma2(sdpropsigma2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(algoritmo_logit(y, nit, beta, sigma2, f, alfa, sdpropbeta, sdpropbeta2, sdpropf, sdpropsigma2, n, p, j, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// algoritmo_probit
List algoritmo_probit(arma::mat y, int nit, arma::mat beta, arma::mat f, arma::colvec sigma2, arma::mat alpha, double C0, double a, double b, double sdpropbeta, double sdpropbeta2, double sdpropf, double sdpropsigma2, bool display_progress);
RcppExport SEXP _fatcat_algoritmo_probit(SEXP ySEXP, SEXP nitSEXP, SEXP betaSEXP, SEXP fSEXP, SEXP sigma2SEXP, SEXP alphaSEXP, SEXP C0SEXP, SEXP aSEXP, SEXP bSEXP, SEXP sdpropbetaSEXP, SEXP sdpropbeta2SEXP, SEXP sdpropfSEXP, SEXP sdpropsigma2SEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nit(nitSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type sdpropbeta(sdpropbetaSEXP);
    Rcpp::traits::input_parameter< double >::type sdpropbeta2(sdpropbeta2SEXP);
    Rcpp::traits::input_parameter< double >::type sdpropf(sdpropfSEXP);
    Rcpp::traits::input_parameter< double >::type sdpropsigma2(sdpropsigma2SEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(algoritmo_probit(y, nit, beta, f, sigma2, alpha, C0, a, b, sdpropbeta, sdpropbeta2, sdpropf, sdpropsigma2, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_beta_jl
double l_priori_beta_jl(double beta, int j, int l, double C0);
RcppExport SEXP _fatcat_l_priori_beta_jl(SEXP betaSEXP, SEXP jSEXP, SEXP lSEXP, SEXP C0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type C0(C0SEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_beta_jl(beta, j, l, C0));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_beta_j
double l_priori_beta_j(arma::rowvec beta, int j, double C0);
RcppExport SEXP _fatcat_l_priori_beta_j(SEXP betaSEXP, SEXP jSEXP, SEXP C0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< double >::type C0(C0SEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_beta_j(beta, j, C0));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_beta
double l_priori_beta(arma::mat beta, double C0);
RcppExport SEXP _fatcat_l_priori_beta(SEXP betaSEXP, SEXP C0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type C0(C0SEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_beta(beta, C0));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_f_li
double l_priori_f_li(double f);
RcppExport SEXP _fatcat_l_priori_f_li(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_f_li(f));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_f_i
double l_priori_f_i(arma::colvec f);
RcppExport SEXP _fatcat_l_priori_f_i(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_f_i(f));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_f
double l_priori_f(arma::mat f);
RcppExport SEXP _fatcat_l_priori_f(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_f(f));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_sigma2_j
double l_priori_sigma2_j(double sigma2, double a, double b);
RcppExport SEXP _fatcat_l_priori_sigma2_j(SEXP sigma2SEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_sigma2_j(sigma2, a, b));
    return rcpp_result_gen;
END_RCPP
}
// l_priori_sigma2
double l_priori_sigma2(arma::colvec sigma2, double a, double b);
RcppExport SEXP _fatcat_l_priori_sigma2(SEXP sigma2SEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(l_priori_sigma2(sigma2, a, b));
    return rcpp_result_gen;
END_RCPP
}
// delta_ijk_probit
double delta_ijk_probit(double alpha, arma::rowvec beta, arma::colvec f, double sigma2);
RcppExport SEXP _fatcat_delta_ijk_probit(SEXP alphaSEXP, SEXP betaSEXP, SEXP fSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(delta_ijk_probit(alpha, beta, f, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// delta_ijk_marginal_probit
double delta_ijk_marginal_probit(double alpha, arma::rowvec beta, double sigma2);
RcppExport SEXP _fatcat_delta_ijk_marginal_probit(SEXP alphaSEXP, SEXP betaSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(delta_ijk_marginal_probit(alpha, beta, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// p_ijk_probit
double p_ijk_probit(arma::rowvec alpha, arma::rowvec beta, arma::colvec f, double sigma2);
RcppExport SEXP _fatcat_p_ijk_probit(SEXP alphaSEXP, SEXP betaSEXP, SEXP fSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(p_ijk_probit(alpha, beta, f, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// p_ijk_marginal_probit
double p_ijk_marginal_probit(arma::rowvec alpha, arma::rowvec beta, double sigma2);
RcppExport SEXP _fatcat_p_ijk_marginal_probit(SEXP alphaSEXP, SEXP betaSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(p_ijk_marginal_probit(alpha, beta, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// l_vero_j_probit
double l_vero_j_probit(arma::rowvec y, arma::rowvec alpha, arma::rowvec beta, arma::mat f, double sigma2);
RcppExport SEXP _fatcat_l_vero_j_probit(SEXP ySEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(l_vero_j_probit(y, alpha, beta, f, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// l_vero_j_marginal_probit
double l_vero_j_marginal_probit(arma::rowvec y, arma::rowvec alpha, arma::rowvec beta, double sigma2);
RcppExport SEXP _fatcat_l_vero_j_marginal_probit(SEXP ySEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(l_vero_j_marginal_probit(y, alpha, beta, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// l_vero_i_probit
double l_vero_i_probit(arma::colvec y, arma::mat alpha, arma::mat beta, arma::colvec f, arma::colvec sigma2);
RcppExport SEXP _fatcat_l_vero_i_probit(SEXP ySEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(l_vero_i_probit(y, alpha, beta, f, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// l_vero_probit
double l_vero_probit(arma::mat y, arma::mat alpha, arma::mat beta, arma::mat f, arma::colvec sigma2);
RcppExport SEXP _fatcat_l_vero_probit(SEXP ySEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP fSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type f(fSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(l_vero_probit(y, alpha, beta, f, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// l_vero_marginal_probit
double l_vero_marginal_probit(arma::mat y, arma::mat alpha, arma::mat beta, arma::colvec sigma2);
RcppExport SEXP _fatcat_l_vero_marginal_probit(SEXP ySEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(l_vero_marginal_probit(y, alpha, beta, sigma2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fatcat_algoritmo_logit", (DL_FUNC) &_fatcat_algoritmo_logit, 14},
    {"_fatcat_algoritmo_probit", (DL_FUNC) &_fatcat_algoritmo_probit, 14},
    {"_fatcat_l_priori_beta_jl", (DL_FUNC) &_fatcat_l_priori_beta_jl, 4},
    {"_fatcat_l_priori_beta_j", (DL_FUNC) &_fatcat_l_priori_beta_j, 3},
    {"_fatcat_l_priori_beta", (DL_FUNC) &_fatcat_l_priori_beta, 2},
    {"_fatcat_l_priori_f_li", (DL_FUNC) &_fatcat_l_priori_f_li, 1},
    {"_fatcat_l_priori_f_i", (DL_FUNC) &_fatcat_l_priori_f_i, 1},
    {"_fatcat_l_priori_f", (DL_FUNC) &_fatcat_l_priori_f, 1},
    {"_fatcat_l_priori_sigma2_j", (DL_FUNC) &_fatcat_l_priori_sigma2_j, 3},
    {"_fatcat_l_priori_sigma2", (DL_FUNC) &_fatcat_l_priori_sigma2, 3},
    {"_fatcat_delta_ijk_probit", (DL_FUNC) &_fatcat_delta_ijk_probit, 4},
    {"_fatcat_delta_ijk_marginal_probit", (DL_FUNC) &_fatcat_delta_ijk_marginal_probit, 3},
    {"_fatcat_p_ijk_probit", (DL_FUNC) &_fatcat_p_ijk_probit, 4},
    {"_fatcat_p_ijk_marginal_probit", (DL_FUNC) &_fatcat_p_ijk_marginal_probit, 3},
    {"_fatcat_l_vero_j_probit", (DL_FUNC) &_fatcat_l_vero_j_probit, 5},
    {"_fatcat_l_vero_j_marginal_probit", (DL_FUNC) &_fatcat_l_vero_j_marginal_probit, 4},
    {"_fatcat_l_vero_i_probit", (DL_FUNC) &_fatcat_l_vero_i_probit, 5},
    {"_fatcat_l_vero_probit", (DL_FUNC) &_fatcat_l_vero_probit, 5},
    {"_fatcat_l_vero_marginal_probit", (DL_FUNC) &_fatcat_l_vero_marginal_probit, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fatcat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
