# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

algoritmo_logit <- function(y, nit, beta, sigma2, f, alfa, sdpropbeta, sdpropbeta2, sdpropf, sdpropsigma2, n, p, j, display_progress = TRUE) {
    .Call('_fatcat_algoritmo_logit', PACKAGE = 'fatcat', y, nit, beta, sigma2, f, alfa, sdpropbeta, sdpropbeta2, sdpropf, sdpropsigma2, n, p, j, display_progress)
}

algoritmo_probit <- function(y, nit, beta, sigma2, f, alfa, sdpropbeta, sdpropbeta2, sdpropf, sdpropsigma2, n, p, j, display_progress = TRUE) {
    .Call('_fatcat_algoritmo_probit', PACKAGE = 'fatcat', y, nit, beta, sigma2, f, alfa, sdpropbeta, sdpropbeta2, sdpropf, sdpropsigma2, n, p, j, display_progress)
}

