# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

probProbit <- function(alfa, beta, f, sigma2) {
    .Call('_fatcat_probProbit', PACKAGE = 'fatcat', alfa, beta, f, sigma2)
}

probLogit <- function(alfa, beta, f, sigma2) {
    .Call('_fatcat_probLogit', PACKAGE = 'fatcat', alfa, beta, f, sigma2)
}

probNominal <- function(beta, f) {
    .Call('_fatcat_probNominal', PACKAGE = 'fatcat', beta, f)
}

logcondcompbetajProbit <- function(f, beta, alfa, sigma2, y, j) {
    .Call('_fatcat_logcondcompbetajProbit', PACKAGE = 'fatcat', f, beta, alfa, sigma2, y, j)
}

logcondcompfiProbit <- function(f, beta, alfa, sigma2, y, i) {
    .Call('_fatcat_logcondcompfiProbit', PACKAGE = 'fatcat', f, beta, alfa, sigma2, y, i)
}

logcondcompsigma2jProbit <- function(f, beta, alfa, sigma2, y, j) {
    .Call('_fatcat_logcondcompsigma2jProbit', PACKAGE = 'fatcat', f, beta, alfa, sigma2, y, j)
}

logcondcompbetajLogit <- function(f, beta, alfa, sigma2, y, j) {
    .Call('_fatcat_logcondcompbetajLogit', PACKAGE = 'fatcat', f, beta, alfa, sigma2, y, j)
}

logcondcompfiLogit <- function(f, beta, alfa, sigma2, y, i) {
    .Call('_fatcat_logcondcompfiLogit', PACKAGE = 'fatcat', f, beta, alfa, sigma2, y, i)
}

logcondcompsigma2jLogit <- function(f, beta, alfa, sigma2, y, j) {
    .Call('_fatcat_logcondcompsigma2jLogit', PACKAGE = 'fatcat', f, beta, alfa, sigma2, y, j)
}

logcondcompbetajkNominal <- function(f, beta, y, j, k) {
    .Call('_fatcat_logcondcompbetajkNominal', PACKAGE = 'fatcat', f, beta, y, j, k)
}

logcondcompfiNominal <- function(f, beta, y, i) {
    .Call('_fatcat_logcondcompfiNominal', PACKAGE = 'fatcat', f, beta, y, i)
}

